# pull official base image
FROM python:3.9.0-alpine

# set work directory
WORKDIR /usr/src/app

# install psycopg2 dependencies
#RUN apk update \
#   && apk add postgresql-dev gcc python3-dev musl-dev zlib-dev jpeg-dev libffi-dev libxml2-dev libxslt-dev

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

RUN apk add --no-cache tzdata
ENV TZ America/Santiago


# fix libraries

#COPY ./fixlib/graphene/utils.py /usr/local/lib/python3.9/site-packages/graphene_django/utils/

# ---

# copy project
COPY . /usr/src/app/

#RUN python manage.py collectstatic --noinput
#RUN python manage.py makemigrations

#migrations
#RUN python manage.py makemigrations
#RUN python manage.py migrate



